### ISSUE TITLE
Unable to launch application from rpm

### ISSUE THREAD

**Issue by cognitus** [SiebenCorgie/Beta-Launcher#9]
when installing rpm there are some errors, the solutions are in this post  https://forums.unrealengine.com/showthread.php?110795-Beta-Launcher-for-Linux&p=614125&viewfull=1#post614125
so, i have the same error described there

`(launcher.py:14211): Gtk-WARNING **: gtkcontainer.c:1174: child property `position' of container class `GtkHeaderBar' is not writable
Traceback (most recent call last):
  File "launcher.py", line 1062, in <module>
    sys.exit(main())
  File "launcher.py", line 1058, in main
    app = GUI()
  File "launcher.py", line 60, in __init__
    self.builder.add_from_file(UIFILE)
GLib.Error: gtk-builder-error-quark: Propiedad no válida: GtkPaned.wide_handle  on line 1256 (11)`

any ideas?

**Comment by cognitus** [comment]
I resolve myself, in file launcher.ui comment the line 1256 `<!--<property name="wide_handle">True</property>-->`

works a little buggy 
![on kde](http://i.imgur.com/tSy8vZC.jpg)

with a lot warning http://pastebin.com/FYYHk5wP, but works!!

**Comment by SiebenCorgie** [comment]
Hi,
Sorry i could not reply faster.

I actually have no idea why you are getting the error. I tested  the launcher RPM on fedora 24. It was working well. 

**May I know your gtk3 version and what bugs you have when commenting out the line?**

The problem why I don't officially support RPMs is, that I don't know how to create them with all the dependencies working.

However I'll try to fix the problem as good as possible.

-siebencorgie

**Comment by cognitus** [comment]
I have installed libgtk+3_0-3.14.8-5 (Mageia 5)
Respect to bugs, when i installed the launcher was need install additional dependencies, so after installed i don't see bugs. except by files *.conf , I had change the settings with text editor because the launcher don't save the settings.

**Comment by SiebenCorgie** [comment]
I had a look at the .ui file. According to glade (which I use to create the ui) it should work on gtk 3.14 . Maybe your workaround is the only solution at the moment. 

I'll add the dependencies to the Readme and the Unreal-Forum thread. 
If I find time I'll try to build a bit more convenient RPMs for the Launcher. At the moment my time is a bit short and I don't have the knowledge on how to support them. As far as I can see the RPMs for Fedora are different to the RPMs from CentOS. 

I hope that is okay for you. If you have other questions please let me know.

**Comment by lahtis** [comment]
Program crashing when webkit not installed. Ubuntu 16.04 LTS

beta-launcher 
Traceback (most recent call last):
  File "launcher.py", line 21, in <module>
    gi.require_version('WebKit', '3.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 102, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit not available

When im installing gir1.2-webkit-3.0. Program working.

**Comment by SiebenCorgie** [comment]
It looks like the Ubuntu dependencies have changed, I'll add them to a new binary release.

**Comment by lahtis** [comment]
Can you update install script in 4.15 version, it has changed.

**Comment by SiebenCorgie** [comment]
How did it change? I installed 4.15 successfully already.
